In [1]:
%pip install matplotlib

Requirement already satisfied: matplotlib in c:\Users\Compu City\anaconda3\Lib\site-packages (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Compu City\anaconda3\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Compu City\anaconda3\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Compu City\anaconda3\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Compu City\anaconda3\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.25 in c:\Users\Compu City\anaconda3\Lib\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in C:\Users\Compu City\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in c:\Users\Compu City\anaconda3\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Compu City\anaconda3\Lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Compu City\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\Compu City\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np

Read DATA

In [3]:
data = pd.read_csv(r'ml_repositories.csv')
data.head()

,id,name,full_name,owner,stars,forks,open_issues,language,created_at,updated_at
0,876064934,ai-engineering-hub,patchy631/ai-engineering-hub,patchy631,37152,6140,124,Jupyter Notebook,2024-10-21 10:43:24+00:00,2026-08-23 17:26:08+00:00
1,784181462,Vane,ItzCrazyKns/Vane,ItzCrazyKns,36402,4039,347,TypeScript,2024-04-09 10:51:32+00:00,2026-08-23 17:23:44+00:00
2,849406496,FinceptTerminal,Fincept-Corporation/FinceptTerminal,Fincept-Corporation,30541,4319,14,C++,2024-08-29 14:38:08+00:00,2026-08-23 17:19:46+00:00
3,828268839,RAG_Techniques,NirDiamant/RAG_Techniques,NirDiamant,29185,3562,14,Jupyter Notebook,2024-07-13 16:08:36+00:00,2026-08-23 17:01:47+00:00
4,854807707,GenAI_Agents,NirDiamant/GenAI_Agents,NirDiamant,23953,4026,12,Jupyter Notebook,2024-09-09 20:10:19+00:00,2026-08-23 15:46:37+00:00

In [4]:
data.columns.tolist()

['id',
 'name',
 'full_name',
 'owner',
 'stars',
 'forks',
 'open_issues',
 'language',
 'created_at',
 'updated_at']

Start Cleaning Data

In [5]:
data['id'] = data['id'].astype(str) 
data['created_at'] = pd.to_datetime(data['created_at']) 
data['updated_at'] = pd.to_datetime(data['updated_at']) 
data['language'] = data['language'].astype(str)

In [6]:
data['created_at'] = pd.to_datetime(data['created_at']).dt.tz_localize(None)
data['updated_at'] = pd.to_datetime(data['updated_at']).dt.tz_localize(None)

data['id'] = data['id'].astype(str)
data['language'] = data['language'].astype(str)

In [7]:
data.head(10)

,id,name,full_name,owner,stars,forks,open_issues,language,created_at,updated_at
0,876064934,ai-engineering-hub,patchy631/ai-engineering-hub,patchy631,37152,6140,124,Jupyter Notebook,2024-10-21 10:43:24,2026-08-23 17:26:08
1,784181462,Vane,ItzCrazyKns/Vane,ItzCrazyKns,36402,4039,347,TypeScript,2024-04-09 10:51:32,2026-08-23 17:23:44
2,849406496,FinceptTerminal,Fincept-Corporation/FinceptTerminal,Fincept-Corporation,30541,4319,14,C++,2024-08-29 14:38:08,2026-08-23 17:19:46
3,828268839,RAG_Techniques,NirDiamant/RAG_Techniques,NirDiamant,29185,3562,14,Jupyter Notebook,2024-07-13 16:08:36,2026-08-23 17:01:47
4,854807707,GenAI_Agents,NirDiamant/GenAI_Agents,NirDiamant,23953,4026,12,Jupyter Notebook,2024-09-09 20:10:19,2026-08-23 15:46:37
5,817326197,screenpipe,screenpipe/screenpipe,screenpipe,21183,2125,97,Rust,2024-06-19 13:23:56,2026-08-23 17:14:14
6,839428333,speech-to-speech,huggingface/speech-to-speech,huggingface,12800,1584,107,Python,2024-08-07 15:32:09,2026-08-23 17:02:43
7,829640443,tensorzero,tensorzero/tensorzero,tensorzero,11721,961,392,Rust,2024-07-16 21:00:53,2026-08-22 18:14:58
8,870554327,Prompt_Engineering,NirDiamant/Prompt_Engineering,NirDiamant,7808,1017,4,Jupyter Notebook,2024-10-10 08:52:12,2026-08-23 16:12:15
9,832647441,agent-squad,2FastLabs/agent-squad,2FastLabs,7742,735,86,Swift,2024-07-23 12:48:30,2026-08-21 10:27:39

Sepreate time from created_at & uploaded_at columns

In [8]:
data['created_at'] = pd.to_datetime(data['created_at'])
data['updated_at'] = pd.to_datetime(data['updated_at'])

data['time_updated_at'] = data['updated_at'].dt.time
data['time_created_at'] = data['created_at'].dt.time 

data['updated_at'] = data['updated_at'].dt.date
data['created_at'] = data['created_at'].dt.date

In [9]:
data.head(5)

,id,name,full_name,owner,stars,forks,open_issues,language,created_at,updated_at,time_updated_at,time_created_at
0,876064934,ai-engineering-hub,patchy631/ai-engineering-hub,patchy631,37152,6140,124,Jupyter Notebook,2024-10-21,2026-08-23,17:26:08,10:43:24
1,784181462,Vane,ItzCrazyKns/Vane,ItzCrazyKns,36402,4039,347,TypeScript,2024-04-09,2026-08-23,17:23:44,10:51:32
2,849406496,FinceptTerminal,Fincept-Corporation/FinceptTerminal,Fincept-Corporation,30541,4319,14,C++,2024-08-29,2026-08-23,17:19:46,14:38:08
3,828268839,RAG_Techniques,NirDiamant/RAG_Techniques,NirDiamant,29185,3562,14,Jupyter Notebook,2024-07-13,2026-08-23,17:01:47,16:08:36
4,854807707,GenAI_Agents,NirDiamant/GenAI_Agents,NirDiamant,23953,4026,12,Jupyter Notebook,2024-09-09,2026-08-23,15:46:37,20:10:19

In [10]:
current_date = pd.to_datetime("2026-08-23", utc=True) 
data['repo_age_days'] = (current_date - pd.to_datetime(data['created_at'], utc=True)).dt.days

In [11]:
data.head(5)

,id,name,full_name,owner,stars,forks,open_issues,language,created_at,updated_at,time_updated_at,time_created_at,repo_age_days
0,876064934,ai-engineering-hub,patchy631/ai-engineering-hub,patchy631,37152,6140,124,Jupyter Notebook,2024-10-21,2026-08-23,17:26:08,10:43:24,671
1,784181462,Vane,ItzCrazyKns/Vane,ItzCrazyKns,36402,4039,347,TypeScript,2024-04-09,2026-08-23,17:23:44,10:51:32,866
2,849406496,FinceptTerminal,Fincept-Corporation/FinceptTerminal,Fincept-Corporation,30541,4319,14,C++,2024-08-29,2026-08-23,17:19:46,14:38:08,724
3,828268839,RAG_Techniques,NirDiamant/RAG_Techniques,NirDiamant,29185,3562,14,Jupyter Notebook,2024-07-13,2026-08-23,17:01:47,16:08:36,771
4,854807707,GenAI_Agents,NirDiamant/GenAI_Agents,NirDiamant,23953,4026,12,Jupyter Notebook,2024-09-09,2026-08-23,15:46:37,20:10:19,713